--- #YAML:1.0
name: JIRA-Client
version: 0.28
abstract: An extended interface to JIRA's SOAP API.
license: perl
author: Gustavo Chaves <gnustavo@cpan.org>
generated_by: Gustavo Chaves
distribution_type: module
requires:
    IO::Socket: 0
    SOAP::Lite: 0
    Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://code.google.com/p/jira-client/
  repository: http://jira-client.googlecode.com/svn/trunk/
meta-spec:
    version: 1.3
    url: http://module-build.sourceforge.net/META-spec-v1.3.html
